name: ci
on:
  pull_request:
  push:
    branches:
    - master
  # schedule:
  # - cron: '00 01 * * *'
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        # - pinned
        # - stable
        # - beta
        # - nightly
        - win-gnu
        # - linux
        # - macos
        include:
        # - build: pinned
        #   os: windows-2019
        #   rust: 1.34.0
        # - build: stable
        #   os: windows-2019
        #   rust: stable
        # - build: beta
        #   os: windows-2019
        #   rust: beta
        # - build: nightly
        #   os: ubuntu-18.04
        #   rust: nightly
        - build: win-gnu
          os: windows-2019
          rust: stable-x86_64-gnu
        # - build: linux
        #   os: ubuntu-18.04
        #   rust: stable
        # - build: macos
        #   os: macos-latest
        #   rust: stable
    steps:
    - name: Install msys2
      id: install-msys2
      uses: numworks/setup-msys2@v1
    - run: msys2do pacman --noconfirm -S mingw-w64-x86_64-pkg-config mingw-w64-x86_64-cfitsio
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    # - name: Install Rust
    #   uses: hecrj/setup-rust-action@v1
    #   with:
    #     rust-version: ${{ matrix.rust }}
    - run: msys2do curl --proto '=https' --tlsv1.2 -LO https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe
    - run: msys2do ./rustup-init.exe --default-toolchain stable --profile default -y
    - run: msys2do cargo build --manifest-path fitsio/Cargo.toml --verbose
    # - run: cargo doc --manifest-path fitsio/Cargo.toml --verbose
    # - run: cargo test --manifest-path fitsio/Cargo.toml --verbose

  # rustfmt:
  #   name: rustfmt
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 1
  #   - name: Install Rust
  #     uses: hecrj/setup-rust-action@v1
  #     with:
  #       rust-version: stable
  #   - name: Install rustfmt
  #     run: rustup component add rustfmt
  #   - name: Check formatting
  #     run: |
  #       cargo fmt --all -- --check
